<a href="https://colab.research.google.com/github/tecXworld/Machine-Learning-and-Information-Retrieval/blob/main/2_Single_Feature_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing

In [ ]:
temp=['hot','hot','mild','mild','cold','cold','mild','hot']

play=['yes','no','yes','no','no','no','yes','yes']

In [ ]:
le = preprocessing.LabelEncoder()

In [ ]:
temp_encoded=le.fit_transform(temp)

In [ ]:
print(temp_encoded) ##0-cold , 1-hot, 2-mild

[1 1 2 2 0 0 2 1]


In [ ]:
label=le.fit_transform(play)

In [ ]:
print(label); #0-reject , 1- accept

[1 0 1 0 0 0 1 1]


In [ ]:
model = GaussianNB()

In [ ]:
temp_encoded=temp_encoded.reshape(-1,1);
print(temp_encoded)

[[1]
 [1]
 [2]
 [2]
 [0]
 [0]
 [2]
 [1]]


In [ ]:
model.fit(temp_encoded,label)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
predicted= model.predict([[1]])   #0-cold, 1-hot, 2-mild

In [ ]:
if(predicted==1):
  print("Yes")
else:
  print("No")

Yes
